name: blogue
version: '0.1.0.0'
dependencies:
- base ==4.*
- process ==1.6.*
- hakyll ==4.10.*
- hakyll-contrib-hyphenation ==0.1.0.*
# - hakyll-sass >=0.2.3
- hsass >=0.4.0
- aeson >=1.0.2.1
- bytestring >=0.10.8.1
- containers >=0.5.7.1
- pandoc-sidenote >= 0.19.0.0
executables:
  site:
    main: site.hs
    ghc-options: -threaded
