name: blogue
version: '0.1.0.0'
dependencies:
- base ==4.*
- process ==1.6.*
- hakyll >= 4.12.0
- pandoc >= 2.2.1
- pandoc-types >= 1.17.5.1
# - hakyll-sass >=0.2.3
- hsass >=0.4.0
- aeson >=1.0.2.1
- bytestring >=0.10.8.1
- containers >=0.5.7.1
- text
executables:
  site:
    main: site.hs
    ghc-options: -threaded
