version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4 # Based on debian stretch

    steps:
      - checkout
      - run: git merge master
      - run: |
          set -euxo pipefail
          apt-get update && apt-get install -y apt-transport-https
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          echo deb https://deb.nodesource.com/node_12.x buster main | tee /etc/apt/sources.list.d/nodesource.list
          apt-get update
          apt-get install -y time virtualenv nodejs yarn graphviz

      - restore_cache:
          keys:
            - home-stack-{{ checksum "stack.yaml" }}
            - stack
      - restore_cache:
          keys:
            - work-stack-{{ checksum "stack.yaml" }}-{{checksum "package.yaml" }}
            - stack
      - run: stack setup

      - run: env time -v stack build -j 8
      - save_cache:
          key: home-stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
      - save_cache:
          key: work-stack-{{ checksum "stack.yaml" }}-{{checksum "package.yaml" }}
          paths:
            - .stack-work

      - run: stack exec -- slick

      - store_artifacts:
          path: dist
          destination: dist