version: 2
jobs:
  build:
    docker:
      - image: haskell:8.8 # Based on debian buster

    steps:
      - checkout
      - run: |
          upstream=${CIRCLE_REPOSITORY_URL:-$(git remote  get-url origin)}
          git config --global user.email "circleci@invalid.example"
          git config --global user.name "CircleCI build for ${upstream}"
          git merge --no-edit --no-ff origin/main
      - run: |
          set -euxo pipefail
          apt-get update && apt-get install -y apt-transport-https
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          echo deb https://deb.nodesource.com/node_12.x buster main | tee /etc/apt/sources.list.d/nodesource.list
          apt-get update
          apt-get install -y time virtualenv nodejs yarn graphviz

      - run: echo 1 > ~/cache-version
      - restore_cache:
          keys:
            - home-stack-{{ checksum "~/cache-version" }}-{{ checksum "stack.yaml" }}-{{checksum "package.yaml" }}
            - home-stack-{{ checksum "~/cache-version" }}-{{ checksum "stack.yaml" }}
      - restore_cache:
          keys:
            - work-stack-{{ checksum "~/cache-version" }}-{{ checksum "stack.yaml" }}-{{checksum "package.yaml" }}
      - run: stack setup

      - run: env time -v stack build -j 8
      - save_cache:
          key: home-stack-{{ checksum "~/cache-version" }}-{{ checksum "stack.yaml" }}-{{checksum "package.yaml" }}
          paths:
            - ~/.stack
      - save_cache:
          key: work-stack-{{ checksum "~/cache-version" }}-{{ checksum "stack.yaml" }}-{{checksum "package.yaml" }}
          paths:
            - .stack-work

      - run: stack exec -- slick

      - run: tar Jcvf dist.tar.xz dist

      - store_artifacts:
          path: dist.tar.xz
