version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4

    steps:
      - checkout
      - run: git merge master
      - run: apt-get update && apt-get install time

      - restore_cache:
          key: stack

      - run: time -v ./bin/build.sh

      - save_cache:
          key: stack-{{ .BuildNum }}
          paths:
            - ~/.stack
            - .stack-work

      - store_artifacts:
          path: dist
          destination: dist