version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.26

    steps:
      - checkout
      - run: git merge master

      - run:
          name: Greeting
          command: echo Hi!
