version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4

    steps:
      - checkout
      - run: git merge master
      - run: |
          set -euxo pipefail
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

          apt-get update
          apt-get install time virtualenv yarn

      - restore_cache:
          key: stack

      - run: env time -v stack build -j 8
      - save_cache:
          key: stack-{{ .BuildNum }}
          paths:
            - ~/.stack
            - .stack-work

      - run: stack exec -- slick

      - store_artifacts:
          path: dist
          destination: dist