version: 2
jobs:
  build:
    docker:
      - image: haskell:8.4

    steps:
      - checkout
      - run: git merge master

      - restore_cache:
          key: stack

      - run: ./bin/build.sh

      - save_cache:
          key: stack-{{ .BuildNum }}
          paths:
            - ~/.stack
            - .stack-work
